package config

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/a-pav/i3title/internal/bbuf"
)

// Config is the Config struct.
type Config struct {
	BufSize    uint16 `json:"buffer_size"` // Buffer size of both stdin scanner and stdout printer.
	MaxWidth   int    `json:"max_width"`   // Maximum width of printed report in characters.
	Format     string `json:"format"`
	ModeFormat string `json:"mode_format"` // Pango styling to be used for i3 modes.
	Pipe       string `json:"pipe"`        // FIFO named pipe for sending messages to overwrite the report.

	// Specific to `i3bar` protocol, we don't use them.
	Align     string    `json:"align"`
	Separator rawString `json:"separator"` // boolean
	MinWidth  rawString `json:"min_width"` // integer

	formatIndex     int `json:"-"` // Index of string `%s` inside [Config.Format].
	modeFormatIndex int `json:"-"` // Index of string `%s` inside [Config.ModeFormat].
	modeFormatWidth int `json:"-"` // Width of characters that will be added to report as the result of wrapping raw i3 mode in [Config.ModeFormat].
}

func (c *Config) WriteReport(report *bbuf.BasicBuffer, title, mode string) {
	mw := 0 // mode visible width.
	if c.ModeFormat != "" && mode != "default" {
		mw = len([]rune(mode)) + c.modeFormatWidth

		report.WriteString(c.ModeFormat[:c.modeFormatIndex])
		report.WriteString(mode)
		report.WriteString(c.ModeFormat[c.modeFormatIndex+2:]) // 2 == len("%s")
	}
	report.WriteTextString(title, c.MaxWidth-mw)
}

func (c *Config) Print(line, fullText []byte) int {
	n := 0
	n += copy(line[n:], `{"name":"i3title","markup":"pango","align":"`)
	n += copy(line[n:], c.Align) // "left"
	n += copy(line[n:], `","separator":`)
	n += copy(line[n:], c.Separator) // false
	n += copy(line[n:], `,"min_width":`)
	n += copy(line[n:], c.MinWidth) // 1234
	n += copy(line[n:], `,"full_text":"`)
	n += copy(line[n:], c.Format[:c.formatIndex]) // <span>
	n += copy(line[n:], fullText)
	n += copy(line[n:], c.Format[c.formatIndex+2:]) // </span>
	n += copy(line[n:], `"},`)

	return n
}

type rawString string

func (rs *rawString) UnmarshalJSON(data []byte) error {
	*rs = rawString(data)
	return nil
}

func (rs rawString) MarshalJSON() ([]byte, error) {
	return []byte(rs), nil
}

// newConfig return a usable config.
func newConfig() *Config {
	return &Config{
		BufSize:     3000, // more than it's necessary
		MaxWidth:    60,   // less than it's possible
		Align:       "left",
		Separator:   "false",
		MinWidth:    "400",
		Format:      "%s",
		formatIndex: 0,
	}
}

func Load() (*Config, error) {
	cfg := newConfig()
	defer func() {
		save(cfg)
		discard(cfg)
	}()

	if path, err := getPath(); err != nil {
		log.Printf("config: %s", err)
	} else {
		if err := read(path, cfg); err != nil {
			return nil, err
		}
		log.Printf("config: loaded from: %s", path)
	}

	if i := strings.Index(cfg.ModeFormat, "%s"); i >= 0 {
		cfg.modeFormatIndex = i
		// Strip any char that doesn't add to the width.
		raw := regexp.MustCompile("</?[^>]+>").ReplaceAllString(cfg.ModeFormat, "")
		cfg.modeFormatWidth = len([]rune(raw)) - len("%s")
	} else {
		cfg.modeFormatIndex = i
	}

	if i := strings.Index(cfg.Format, "%s"); i >= 0 {
		cfg.formatIndex = i
	} else { // reenforce the defaults
		cfg.Format = "%s"
		cfg.formatIndex = 0
	}

	return cfg, nil
}

func read(path string, cfg *Config) error {
	bs, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("config: read: %v", err)
	}
	// Strip comments before decoding.
	bs = regexp.MustCompile(`(?m)^\s*//.*$`).ReplaceAll(bs, nil)

	if err := json.Unmarshal(bs, cfg); err != nil {
		return fmt.Errorf("config: read: %v", err)
	}

	return nil
}

// save stores the config under the user config directory if the file doesn't
// exist already.
func save(cfg *Config) {
	dir, err := os.UserConfigDir()
	if err != nil {
		log.Printf("config: save: os.UserConfigDir(): %s", err)
		return
	}
	dir += "/i3title"
	if err := os.MkdirAll(dir, 0755); err != nil {
		log.Printf("config: save: os.MkdirAll(): %s", err)
		return
	}

	saveEnv(dir, cfg)
	saveJSON(dir, cfg)
}

func saveEnv(dir string, cfg *Config) {
	f, err := os.OpenFile(dir+"/.env", os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0644)
	if err != nil {
		log.Printf("config: save: %s", err)
		return
	}
	defer f.Close()

	_, err = fmt.Fprintf(f, `# Generated by i3title. Do not edit.
I3TITLE_PIPE=%q
I3TITLE_MAX_WIDTH=%d
`,
		cfg.Pipe,
		cfg.MaxWidth,
	)
	if err != nil {
		log.Printf("config: save: %s", err)
		return
	}
}

func saveJSON(dir string, cfg *Config) {
	path := dir + "/config.json"
	f, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0644)
	if err != nil {
		if !os.IsExist(err) {
			log.Printf("config: save: %s", err)
		}
		return
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "\t")
	enc.SetEscapeHTML(false)

	if err := enc.Encode(cfg); err != nil {
		log.Printf("config: save: failed to write: %v", err)
	} else {
		log.Printf("config: save: created at: %s", path)
	}
}

// discard discards parts of the config that are no longer needed.
func discard(c *Config) {}

func getPath() (string, error) {
	if path, provided, err := pathFromArgs(); provided {
		if err != nil {
			return "", err
		}
		return path, fileExists(path)
	}

	if path := os.Getenv("I3TITLE_CONFIG"); path != "" {
		return path, fileExists(path)
	}

	if path, err := os.UserConfigDir(); err == nil {
		path += "/i3title/config.json"
		if err := fileExists(path); err == nil {
			return path, nil
		}
	}

	// Read config file from current working directory.
	if path, err := getwd(); err == nil {
		path += "/config.json"
		if err := fileExists(path); err == nil {
			return path, nil
		}
	}

	return "", fmt.Errorf("failed to get config path")
}

func pathFromArgs() (path string, provided bool, err error) {
	args := os.Args
	for i, arg := range args {
		switch arg {
		case "-c", "-config", "--config":
			if i+1 < len(args) {
				return args[i+1], true, nil
			}
			return "", true, fmt.Errorf("%q flag is present but no path is provided", arg)
		}
		if strings.HasPrefix(arg, "-config=") {
			return strings.TrimPrefix(arg, "-config="), true, nil
		}
		if strings.HasPrefix(arg, "--config=") {
			return strings.TrimPrefix(arg, "--config="), true, nil
		}
	}
	return "", false, nil
}

// getwd returns the executable working directory.
func getwd() (string, error) {
	exePath, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("getwd: executable path: %v", err)
	}
	// Clean up any symlinks in the executable path.
	exeRealpath, err := filepath.EvalSymlinks(exePath)
	if err != nil {
		return "", fmt.Errorf("getwd: executable real path: %v", err)
	}

	return filepath.Dir(exeRealpath), nil
}

// fileExists returns nil if the file path exists and is a regular file. Otherwise
// it returns a non-nil error explaining why.
func fileExists(path string) error {
	if path == "" {
		return fmt.Errorf("file path is empty")
	}

	info, err := os.Stat(path)
	if err != nil {
		return err
	}

	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file (mode: %v)", path, info.Mode())
	}

	return nil // File exists and is regular
}
